# Generated by Django 5.1.6 on 2025-02-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_stage_options_remove_stage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='description',
        ),
    ]
